service: testing

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  addTodo:
    handler: handler.addTodo
    events:
      - http:
          path: /todos
          method: post

  getAllTodos:
    handler: handler.getAllTodos
    events:
      - http:
          path: /todos
          method: get

  updateTodo:
    handler: handler.updateTodo
    events:
      - http:
          path: /todos/{id}
          method: put

  deleteTodo:
    handler: handler.deleteTodo
    events:
      - http:
          path: /todos/{id}
          method: delete
